### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ZenPs** [layeh/barnard#15] opened 2016-08-17 20:04 UTC
Hi, so i have a raspberry 2 but i'm not able to install it. I want to have this so i can autostart the client at boot and autoconnect it to my local raspberry server (another rasp). Could you guys please give me all the links to install it? Thanks

**Comment by njaxx** [comment] 2016-08-19 16:38
#6 has some guidelines.  It's good that this is at the top of the issue stack, it should probably get moved into the readme if the maintainer returns.

**Comment by bontibon** [comment] 2016-08-19 16:55
dupe of #6

**Closed by bontibon** 2016-08-19 16:55 UTC
