### ISSUE TITLE
How to enable audio options?

### ISSUE THREAD

**Issue by kameshraj** [layeh/barnard#17] opened 2016-09-08 22:10 UTC
Hi
I checked out the issue titled instructions and assumed Fn1 is the key to have push to talk enabled. The program crashes when I press Fn1. 

Is it possible to enable audio all the time instead if push to talk?

Thanks

**Comment by bontibon** [comment] 2018-05-08 21:17
Duplicate of #8.

**Closed by bontibon** 2018-05-08 21:17 UTC
